### ISSUE TITLE
Mapping additional Data

### ISSUE THREAD

**Issue by melihyazgan** [DerrickXuNu/OpenCOOD#135]
Hi,
thank you for the framework!
I want to map bev_static_png, which is road segmentation, available in additional data file in google drive, to the lidar point clouds to distinguish road and non-road points. To do that I thought the additional.yaml file can give me the calibration parameters but the yaml file is not understandable. For example:

```
bev_sem_cam:
  cords:
  - -167.9626007080078
  - 250.52484130859375
  - 115.91366577148438
  - -177.92543029785156
  - 177.96302795410156
  - -90.0
  intrinsic: !!python/object/apply:numpy.core.multiarray._reconstruct
    args:
    - *id001
    - !!python/tuple
      - 0
    - !!binary |
      Yg==
    state: !!python/tuple
    - 1
    - !!python/tuple
      - 3
      - 3
    - *id003
    - false
    - !!binary |
      5p0/M09Qg0AAAAAAAAAAAAAAAAAAAHBAAAAAAAAAAADmnT8zT1CDQAAAAAAAAHBAAAAAAAAAAAAA
      AAAAAAAAAAAAAAAAAPA/
```
Am I missing something? Can anyone give me a hint?
Regards,
Melih
